walkdir: fd
delay: 750
commands:
  - key: "vs"
    command: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\devenv.exe"
    extension: "sln"
    command_arg: "file"
  - key: "code"
    command: "code"
    extension: "sln"
    command_arg: "directory"
